### ISSUE TITLE
Un-installing beta and installing beta2 resulted in below error

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-distribution#382] opened 2019-12-18 11:10 UTC
**Description:**

After installing ballerina when I do ballerina -v. I get the below.

/usr/bin/ballerina: line 76: /usr/lib/ballerina/bin/../distributions/jballerina-1.1.0-beta/bin/./ballerina: No such file or directory
Command 0.8.0

**Comment by keizer619** [comment] 2019-12-18 14:53
I tried in an ubuntu machine by installing beta and reinstalling beta2, but unfortunately could not reproduce the issue.

**Comment by keizer619** [comment] 2021-11-30 10:56
This is not reproduce i am closing this, if there are any concerns please feel free to reopen

**Closed by keizer619** 2021-11-30 10:56 UTC
Labels: Type/Bug, Priority/Blocker, Team/DevTools, Area/CLI
