### ISSUE TITLE
Duplicate messages with pull, when pulled version available in the local. 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-distribution#270] opened 2019-12-09 10:47 UTC
**Description:**
Steps to reproduce. 

```
C:\Users\hasitha\git\gits>ballerina dist fetch jballerina-1.0.4
Downloading jballerina-1.0.4 100% [============================================================================================================================================================================] 95/95 (0:02:44 / 0:00:00)

jballerina-1.0.4 is installed. Please execute "ballerina dist use jballerina-1.0.4" to use as the default

C:\Users\hasitha\git\gits>ballerina dist pull jballerina-1.0.4
Using jballerina-1.0.4
Using jballerina-1.0.4
````

**Comment by warunalakshitha** [comment] 2019-12-10 10:01
Duplicate of https://github.com/ballerina-platform/ballerina-distribution/issues/252

**Closed by warunalakshitha** 2019-12-10 10:01 UTC
Labels: Type/Bug
