### ISSUE TITLE
Incorrect grammer in error message in `Status code response records` BBE

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3482] opened 2022-11-17 21:59 UTC
**Description:**

$subject in [1] 

`album is already exist` should be changed to `album already exists`

[1] https://pre-prod.ballerina.io/learn/by-example/http-status-code-record/

**Comment by chamil321** [comment] 2022-11-23 04:50
The issue is fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3509/files#diff-f449bd762db467b02ee1ae455ada6981444e03a3ffd1a748a7b45246809adf42R27

**Closed by chamil321** 2022-11-23 04:50 UTC
Labels: Type/Bug, Area/BBE

**Comment by anupama-pathirage** [comment] 2022-11-23 06:11
@chamil321 Reason lable is missing
